apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ .Values.name | quote }}
  labels:
    {{- include "helm-library.labels" . | nindent 4 }}
  annotations:
    {{- if .Values.ingress.host }}
    cert-manager.io/cluster-issuer: {{ .Values.ingress.certIssuer }}
    kubernetes.io/ingress.class: {{ .Values.ingress.class | quote }}
    nginx.ingress.kubernetes.io/proxy-body-size: 0
    {{- end }}
spec:
  tls:
  - hosts:
    - {{ .Values.ingress.host }}
    - www.{{ .Values.ingress.host }}
    secretName: {{ .Values.name }}-tls
  rules:
{{- if .Values.ingress.host }}
  - host: {{ .Values.ingress.host }}
    http:
{{ else }}
  - http:
{{- end }}
      paths:
      - path: /
        backend:
          serviceName: {{ .Values.name | quote }}
          servicePort: {{ .Values.service.port }}
{{- if .Values.ingress.host }}
  - host: www.{{ .Values.ingress.host }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ .Values.name | quote }}
          servicePort: {{ .Values.service.port }}
{{- end }}
