trigger:
  - master
  - main

pr: none

resources:
  repositories:
  - repository: templates
    type: github
    endpoint: John D Watson
    name: johnwatson484/azure-devops-templates

extends:
  template: build.yaml@templates
  parameters:
    repo: sugar-free-healthy-diet
    containerRepository: johnwatson484/sugar-free-healthy-diet
    helmChartPath: helm/sugar-free-healthy-diet
    project: SugarFreeHealthyDiet
    framework: net
