trigger:
- master

pool:
  vmImage: 'windows-2019'

steps:

  - task: SonarQubePrepare@4
    inputs:
      SonarQube: 'SonarQube'
      scannerMode: 'MSBuild'
      projectKey: 'sugar-free-healthy-diet'
      projectName: 'sugar-free-healthy-diet'
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  
  - task: DotNetCoreCLI@2
    inputs:
      command: 'build'
      projects: '**/*.sln'

  - task: SonarQubeAnalyze@4
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))

  - task: SonarQubePublish@4
    inputs:
      pollingTimeoutSec: '300'
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))    

  - task: Bash@3
    inputs:
      targetType: 'inline'
      script: |
        docker-compose -f docker-compose.test.yaml -f docker-compose.test.pipeline.yaml build
        docker-compose -f docker-compose.test.yaml -f docker-compose.test.pipeline.yaml up
