trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:

  - task: UseDotNet@2
    inputs:
      packageType: 'sdk'
      version: '2.2.x'

  - task: SonarQubePrepare@4
    inputs:
      SonarQube: 'SonarQube'
      scannerMode: 'MSBuild'
      projectKey: 'sugar-free-healthy-diet'
      projectName: 'sugar-free-healthy-diet'
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master')) 
  - task: Bash@3
    inputs:
      targetType: 'inline'
      script: |
        docker-compose -f docker-compose.test.yaml build
        docker-compose -f docker-compose.test.yaml up

  - task: Bash@3
    inputs:
      targetType: 'inline'
      script: |
        docker-compose build
  
  - task: SonarQubeAnalyze@4
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))

  - task: SonarQubePublish@4
    inputs:
      pollingTimeoutSec: '300'
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))  
