version: '3.7'
services:
  sugar-free-healthy-diet:
    build: 
      context: .
      dockerfile: Dockerfile-development
    depends_on: 
      - sugar-free-healthy-diet-postgres
    ports:
      - "5000:5000"
      - "5001:5001"
    environment:
      ConnectionStrings__DefaultConnection: "Server=sugar-free-healthy-diet-postgres;Port=5432;Database=sugar_free_healthy_diet;User Id=postgres;Password=postgres;"
    volumes:
      - .:/app
    

  sugar-free-healthy-diet-postgres:
    image: postgres:11.4-alpine
    environment:
      POSTGRES_DB: sugar_free_healthy_diet
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data


volumes:
  postgres_data: {}
