services:
  sugar-free-healthy-diet:
    build:
      context: .
      target: development
    image: sugar-free-healthy-diet-test
    container_name: sugar-free-healthy-diet-test
    entrypoint: dotnet test ./SugarFreeHealthyDiet.Tests/SugarFreeHealthyDiet.Tests.csproj
