version: '3.7'
services:
  sugar-free-healthy-diet:
    build: 
      context: .
      target: development
    depends_on: 
      - sugar-free-healthy-diet-postgres
    environment:
      ConnectionStrings__SugarFreeHealthyDiet: "Server=sugar-free-healthy-diet-postgres;Port=5432;Database=sugar_free_healthy_diet;User Id=postgres;Password=postgres;"
    ports:
      - "5000:5000"
    volumes:
      - ./SugarFreeHealthyDiet:/home/dotnet/SugarFreeHealthyDiet
      - ./SugarFreeHealthyDiet.Tests:/home/dotnet/SugarFreeHealthyDiet.Tests
    

  sugar-free-healthy-diet-postgres:
    image: postgres:12.8-alpine
    environment:
      POSTGRES_DB: sugar_free_healthy_diet
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: {}
