environment: production
name: sugar-free-healthy-diet
image: sugar-free-healthy-diet

container:
  requestMemory: 60Mi
  requestCpu: 60m
  limitMemory: 250Mi
  limitCpu: 250m
  port: 5000
  comPlusEnableDiagnostics: 0

smtp:
  server: smtp.zoho.com
  port: 587

ingress:
  host: sugar-free-healthy-diet.com

deployment: {}

secret:
  secretsPath: /sugar-free-healthy-diet
