environment: development
name: sugar-free-healthy-diet
image: sugar-free-healthy-diet:1.0.0

service:
  port: 80

container:
  imagePullPolicy: IfNotPresent
  requestMemory: 60Mi
  requestCpu: 60m
  limitMemory: 80Mi
  limitCpu: 80m
  readOnlyRootFilesystem: true
  allowPrivilegeEscalation: false
  port: 5000
  comPlusEnableDiagnostics: 0
  connectionString: "User Id=postgres;Password=postgres;Server=sugar-free-healthy-diet-postgres;Port=5432;Database=sugar_free_healthy_diet;"

postgresService:
  postgresHost: sugar-free-healthy-diet-postgres
  postgresExternalName: host.docker.internal
  postgresPort: 5432

ingress:
  class: nginx
  host:
  certIssuer: letsencrypt

deployment:
  restartPolicy: Always
  priorityClassName: low
  replicas: 1
  minReadySeconds: 5
  redeployOnChange: update this field to force a change
  imagePullSecret:
  runAsNonRoot: true
  runAsUser: 1000
