environment: production
name: sugar-free-healthy-diet
image: sugar-free-healthy-diet

container:
  requestMemory: 60Mi
  requestCpu: 60m
  limitMemory: 250Mi
  limitCpu: 250m
  port: 5000
  comPlusEnableDiagnostics: 0
  connectionString: "User Id=postgres;Password=postgres;Server=sugar-free-healthy-diet-postgres;Port=5432;Database=sugar_free_healthy_diet;"

smtp:
  server: smtp.email.com
  port: 587
  username: test@email.com
  password: password

ingress: {}

deployment: {}
